In [140]:
import numpy as np 
import pandas as pd 
import re

In [141]:
data = pd.read_csv("/home/saaho/Mechine_learnig/Dataset/IPL/match_summary.csv")

In [142]:
data

,IPL Edition,Date,Time,Match Details,Team 1,Team 2,Winner,Winning Details
0,2023,2023-03-31,7:30 PM,"GUJARAT TITANS vs CHENNAI SUPER KINGS, 1st Match",GUJARAT TITANS,CHENNAI SUPER KINGS,Gujarat Titans,Gujarat Titans won by 5 wkts
1,2023,2023-04-01,3:30 PM,"PUNJAB KINGS vs KOLKATA KNIGHT RIDERS, 2nd Match",PUNJAB KINGS,KOLKATA KNIGHT RIDERS,Punjab Kings,Punjab Kings won by 7 runs (DLS method)
2,2023,2023-04-01,7:30 PM,"LUCKNOW SUPER GIANTS vs DELHI CAPITALS, 3rd Match",LUCKNOW SUPER GIANTS,DELHI CAPITALS,Lucknow Super Giants,Lucknow Super Giants won by 50 runs
3,2023,2023-04-02,3:30 PM,"SUNRISERS HYDERABAD vs RAJASTHAN ROYALS, 4th M...",SUNRISERS HYDERABAD,RAJASTHAN ROYALS,Rajasthan Royals,Rajasthan Royals won by 72 runs
4,2023,2023-04-02,7:30 PM,"ROYAL CHALLENGERS BANGALORE vs MUMBAI INDIANS,...",ROYAL CHALLENGERS BANGALORE,MUMBAI INDIANS,Royal Challengers Bangalore,Royal Challengers Bangalore won by 8 wkts
...,...,...,...,...,...,...,...,...
1032,2008,2008-05-28,4:00 PM,"ROYAL CHALLENGERS BANGALORE vs MUMBAI INDIANS,...",ROYAL CHALLENGERS BANGALORE,MUMBAI INDIANS,Mumbai Indians,Mumbai Indians won by 9 wickets (with 12 balls...
1033,2008,2008-05-28,8:00 PM,"PUNJAB KINGS vs RAJASTHAN ROYALS, 56th match",PUNJAB KINGS,RAJASTHAN ROYALS,Kings XI Punjab,Kings XI Punjab won by 41 runs
1034,2008,2008-05-30,8:00 PM,"DELHI CAPITALS vs RAJASTHAN ROYALS, 1st Semi-F...",DELHI CAPITALS,RAJASTHAN ROYALS,Rajasthan Royals,Rajasthan Royals won by 105 runs
1035,2008,2008-05-31,8:00 PM,"CHENNAI SUPER KINGS vs PUNJAB KINGS, 2nd Semi-...",CHENNAI SUPER KINGS,PUNJAB KINGS,Chennai Super Kings,Chennai Super Kings won by 9 wickets (with 31 ...
1036,2008,2008-06-01,8:15 PM,"CHENNAI SUPER KINGS vs RAJASTHAN ROYALS, Final",CHENNAI SUPER KINGS,RAJASTHAN ROYALS,Rajasthan Royals,Rajasthan Royals won by 3 wickets (with 0 ball...

In [143]:
data.drop(["Time","Date"], axis=1 , inplace=True)

In [144]:
data

,IPL Edition,Match Details,Team 1,Team 2,Winner,Winning Details
0,2023,"GUJARAT TITANS vs CHENNAI SUPER KINGS, 1st Match",GUJARAT TITANS,CHENNAI SUPER KINGS,Gujarat Titans,Gujarat Titans won by 5 wkts
1,2023,"PUNJAB KINGS vs KOLKATA KNIGHT RIDERS, 2nd Match",PUNJAB KINGS,KOLKATA KNIGHT RIDERS,Punjab Kings,Punjab Kings won by 7 runs (DLS method)
2,2023,"LUCKNOW SUPER GIANTS vs DELHI CAPITALS, 3rd Match",LUCKNOW SUPER GIANTS,DELHI CAPITALS,Lucknow Super Giants,Lucknow Super Giants won by 50 runs
3,2023,"SUNRISERS HYDERABAD vs RAJASTHAN ROYALS, 4th M...",SUNRISERS HYDERABAD,RAJASTHAN ROYALS,Rajasthan Royals,Rajasthan Royals won by 72 runs
4,2023,"ROYAL CHALLENGERS BANGALORE vs MUMBAI INDIANS,...",ROYAL CHALLENGERS BANGALORE,MUMBAI INDIANS,Royal Challengers Bangalore,Royal Challengers Bangalore won by 8 wkts
...,...,...,...,...,...,...
1032,2008,"ROYAL CHALLENGERS BANGALORE vs MUMBAI INDIANS,...",ROYAL CHALLENGERS BANGALORE,MUMBAI INDIANS,Mumbai Indians,Mumbai Indians won by 9 wickets (with 12 balls...
1033,2008,"PUNJAB KINGS vs RAJASTHAN ROYALS, 56th match",PUNJAB KINGS,RAJASTHAN ROYALS,Kings XI Punjab,Kings XI Punjab won by 41 runs
1034,2008,"DELHI CAPITALS vs RAJASTHAN ROYALS, 1st Semi-F...",DELHI CAPITALS,RAJASTHAN ROYALS,Rajasthan Royals,Rajasthan Royals won by 105 runs
1035,2008,"CHENNAI SUPER KINGS vs PUNJAB KINGS, 2nd Semi-...",CHENNAI SUPER KINGS,PUNJAB KINGS,Chennai Super Kings,Chennai Super Kings won by 9 wickets (with 31 ...
1036,2008,"CHENNAI SUPER KINGS vs RAJASTHAN ROYALS, Final",CHENNAI SUPER KINGS,RAJASTHAN ROYALS,Rajasthan Royals,Rajasthan Royals won by 3 wickets (with 0 ball...

In [145]:
data.drop(['Winning Details'] ,axis=1, inplace=True)

In [146]:
data

,IPL Edition,Match Details,Team 1,Team 2,Winner
0,2023,"GUJARAT TITANS vs CHENNAI SUPER KINGS, 1st Match",GUJARAT TITANS,CHENNAI SUPER KINGS,Gujarat Titans
1,2023,"PUNJAB KINGS vs KOLKATA KNIGHT RIDERS, 2nd Match",PUNJAB KINGS,KOLKATA KNIGHT RIDERS,Punjab Kings
2,2023,"LUCKNOW SUPER GIANTS vs DELHI CAPITALS, 3rd Match",LUCKNOW SUPER GIANTS,DELHI CAPITALS,Lucknow Super Giants
3,2023,"SUNRISERS HYDERABAD vs RAJASTHAN ROYALS, 4th M...",SUNRISERS HYDERABAD,RAJASTHAN ROYALS,Rajasthan Royals
4,2023,"ROYAL CHALLENGERS BANGALORE vs MUMBAI INDIANS,...",ROYAL CHALLENGERS BANGALORE,MUMBAI INDIANS,Royal Challengers Bangalore
...,...,...,...,...,...
1032,2008,"ROYAL CHALLENGERS BANGALORE vs MUMBAI INDIANS,...",ROYAL CHALLENGERS BANGALORE,MUMBAI INDIANS,Mumbai Indians
1033,2008,"PUNJAB KINGS vs RAJASTHAN ROYALS, 56th match",PUNJAB KINGS,RAJASTHAN ROYALS,Kings XI Punjab
1034,2008,"DELHI CAPITALS vs RAJASTHAN ROYALS, 1st Semi-F...",DELHI CAPITALS,RAJASTHAN ROYALS,Rajasthan Royals
1035,2008,"CHENNAI SUPER KINGS vs PUNJAB KINGS, 2nd Semi-...",CHENNAI SUPER KINGS,PUNJAB KINGS,Chennai Super Kings
1036,2008,"CHENNAI SUPER KINGS vs RAJASTHAN ROYALS, Final",CHENNAI SUPER KINGS,RAJASTHAN ROYALS,Rajasthan Royals

In [147]:
mt = data["Match Details"]

In [148]:
mt

0        GUJARAT TITANS vs CHENNAI SUPER KINGS, 1st Match
1        PUNJAB KINGS vs KOLKATA KNIGHT RIDERS, 2nd Match
2       LUCKNOW SUPER GIANTS vs DELHI CAPITALS, 3rd Match
3       SUNRISERS HYDERABAD vs RAJASTHAN ROYALS, 4th M...
4       ROYAL CHALLENGERS BANGALORE vs MUMBAI INDIANS,...
                              ...
1032    ROYAL CHALLENGERS BANGALORE vs MUMBAI INDIANS,...
1033         PUNJAB KINGS vs RAJASTHAN ROYALS, 56th match
1034    DELHI CAPITALS vs RAJASTHAN ROYALS, 1st Semi-F...
1035    CHENNAI SUPER KINGS vs PUNJAB KINGS, 2nd Semi-...
1036       CHENNAI SUPER KINGS vs RAJASTHAN ROYALS, Final
Name: Match Details, Length: 1037, dtype: object

In [149]:
mt[1036]

'CHENNAI SUPER KINGS vs RAJASTHAN ROYALS, Final'

In [150]:
pattern_semi_final = re.compile(r'Semi')
pattern_final = re.compile(r'Final')

match_details = mt.apply(lambda x: "Semi Final" if pattern_semi_final.search(x) else ("Final" if pattern_final.search(x) else x))

In [151]:
match_details

0        GUJARAT TITANS vs CHENNAI SUPER KINGS, 1st Match
1        PUNJAB KINGS vs KOLKATA KNIGHT RIDERS, 2nd Match
2       LUCKNOW SUPER GIANTS vs DELHI CAPITALS, 3rd Match
3       SUNRISERS HYDERABAD vs RAJASTHAN ROYALS, 4th M...
4       ROYAL CHALLENGERS BANGALORE vs MUMBAI INDIANS,...
                              ...
1032    ROYAL CHALLENGERS BANGALORE vs MUMBAI INDIANS,...
1033         PUNJAB KINGS vs RAJASTHAN ROYALS, 56th match
1034                                           Semi Final
1035                                           Semi Final
1036                                                Final
Name: Match Details, Length: 1037, dtype: object

In [152]:
pattern_final = re.compile(r'Final')
pattern_semi_final = re.compile(r'Semi')
pattern_eliminator = re.compile(r'Eliminator')
pattern_qualifier = re.compile(r'Qualifier')

match_details = match_details.apply(lambda x: x if any(pattern.search(x) for pattern in [pattern_final, pattern_semi_final, pattern_eliminator, pattern_qualifier]) else "Leaugh Match")

In [153]:
match_details

0       Leaugh Match
1       Leaugh Match
2       Leaugh Match
3       Leaugh Match
4       Leaugh Match
            ...
1032    Leaugh Match
1033    Leaugh Match
1034      Semi Final
1035      Semi Final
1036           Final
Name: Match Details, Length: 1037, dtype: object

In [154]:
match_details[72]

'GUJARAT TITANS vs MUMBAI INDIANS, Qualifier 2'

In [155]:
pattern_semi_final = re.compile(r'Qualifier 2')
pattern_final = re.compile(r'Qualifier 1')

match_details = match_details.apply(lambda x: "Qualifier 2" if pattern_semi_final.search(x) else ("Qualifier 1" if pattern_final.search(x) else x))

In [156]:
match_details

0       Leaugh Match
1       Leaugh Match
2       Leaugh Match
3       Leaugh Match
4       Leaugh Match
            ...
1032    Leaugh Match
1033    Leaugh Match
1034      Semi Final
1035      Semi Final
1036           Final
Name: Match Details, Length: 1037, dtype: object

In [157]:
match_details[72]

'Qualifier 2'

In [158]:
pattern_final = re.compile(r'Final')
pattern_semi_final = re.compile(r'Semi')
pattern_eliminator = re.compile(r'Leaugh Match')
pattern_qualifier = re.compile(r'Qualifier')

match_detail = match_details.apply(lambda x: x if any(pattern.search(x) for pattern in [pattern_final, pattern_semi_final, pattern_eliminator, pattern_qualifier]) else "Eliminator")

In [159]:
match_detail
# Filter rows containing "Eliminator"
eliminator_rows = match_detail[match_details.str.contains("Eliminator")]

In [160]:
eliminator_rows

71     Eliminator
146    Eliminator
208    Eliminator
270    Eliminator
330    Eliminator
390    Eliminator
450    Eliminator
510    Eliminator
570    Eliminator
630    Eliminator
706    Eliminator
782    Eliminator
856    Eliminator
Name: Match Details, dtype: object

In [161]:
match_detail

0       Leaugh Match
1       Leaugh Match
2       Leaugh Match
3       Leaugh Match
4       Leaugh Match
            ...
1032    Leaugh Match
1033    Leaugh Match
1034      Semi Final
1035      Semi Final
1036           Final
Name: Match Details, Length: 1037, dtype: object

In [162]:
new_data = data

In [163]:
new_data

,IPL Edition,Match Details,Team 1,Team 2,Winner
0,2023,"GUJARAT TITANS vs CHENNAI SUPER KINGS, 1st Match",GUJARAT TITANS,CHENNAI SUPER KINGS,Gujarat Titans
1,2023,"PUNJAB KINGS vs KOLKATA KNIGHT RIDERS, 2nd Match",PUNJAB KINGS,KOLKATA KNIGHT RIDERS,Punjab Kings
2,2023,"LUCKNOW SUPER GIANTS vs DELHI CAPITALS, 3rd Match",LUCKNOW SUPER GIANTS,DELHI CAPITALS,Lucknow Super Giants
3,2023,"SUNRISERS HYDERABAD vs RAJASTHAN ROYALS, 4th M...",SUNRISERS HYDERABAD,RAJASTHAN ROYALS,Rajasthan Royals
4,2023,"ROYAL CHALLENGERS BANGALORE vs MUMBAI INDIANS,...",ROYAL CHALLENGERS BANGALORE,MUMBAI INDIANS,Royal Challengers Bangalore
...,...,...,...,...,...
1032,2008,"ROYAL CHALLENGERS BANGALORE vs MUMBAI INDIANS,...",ROYAL CHALLENGERS BANGALORE,MUMBAI INDIANS,Mumbai Indians
1033,2008,"PUNJAB KINGS vs RAJASTHAN ROYALS, 56th match",PUNJAB KINGS,RAJASTHAN ROYALS,Kings XI Punjab
1034,2008,"DELHI CAPITALS vs RAJASTHAN ROYALS, 1st Semi-F...",DELHI CAPITALS,RAJASTHAN ROYALS,Rajasthan Royals
1035,2008,"CHENNAI SUPER KINGS vs PUNJAB KINGS, 2nd Semi-...",CHENNAI SUPER KINGS,PUNJAB KINGS,Chennai Super Kings
1036,2008,"CHENNAI SUPER KINGS vs RAJASTHAN ROYALS, Final",CHENNAI SUPER KINGS,RAJASTHAN ROYALS,Rajasthan Royals

In [164]:
other_data = new_data.drop(columns=["Match Details"] ,axis=1)

In [165]:
other_data

,IPL Edition,Team 1,Team 2,Winner
0,2023,GUJARAT TITANS,CHENNAI SUPER KINGS,Gujarat Titans
1,2023,PUNJAB KINGS,KOLKATA KNIGHT RIDERS,Punjab Kings
2,2023,LUCKNOW SUPER GIANTS,DELHI CAPITALS,Lucknow Super Giants
3,2023,SUNRISERS HYDERABAD,RAJASTHAN ROYALS,Rajasthan Royals
4,2023,ROYAL CHALLENGERS BANGALORE,MUMBAI INDIANS,Royal Challengers Bangalore
...,...,...,...,...
1032,2008,ROYAL CHALLENGERS BANGALORE,MUMBAI INDIANS,Mumbai Indians
1033,2008,PUNJAB KINGS,RAJASTHAN ROYALS,Kings XI Punjab
1034,2008,DELHI CAPITALS,RAJASTHAN ROYALS,Rajasthan Royals
1035,2008,CHENNAI SUPER KINGS,PUNJAB KINGS,Chennai Super Kings
1036,2008,CHENNAI SUPER KINGS,RAJASTHAN ROYALS,Rajasthan Royals

In [166]:
new_data = pd.concat([data,match_detail],axis=1)

In [167]:
new_data

,IPL Edition,Match Details,Team 1,Team 2,Winner,Match Details
0,2023,"GUJARAT TITANS vs CHENNAI SUPER KINGS, 1st Match",GUJARAT TITANS,CHENNAI SUPER KINGS,Gujarat Titans,Leaugh Match
1,2023,"PUNJAB KINGS vs KOLKATA KNIGHT RIDERS, 2nd Match",PUNJAB KINGS,KOLKATA KNIGHT RIDERS,Punjab Kings,Leaugh Match
2,2023,"LUCKNOW SUPER GIANTS vs DELHI CAPITALS, 3rd Match",LUCKNOW SUPER GIANTS,DELHI CAPITALS,Lucknow Super Giants,Leaugh Match
3,2023,"SUNRISERS HYDERABAD vs RAJASTHAN ROYALS, 4th M...",SUNRISERS HYDERABAD,RAJASTHAN ROYALS,Rajasthan Royals,Leaugh Match
4,2023,"ROYAL CHALLENGERS BANGALORE vs MUMBAI INDIANS,...",ROYAL CHALLENGERS BANGALORE,MUMBAI INDIANS,Royal Challengers Bangalore,Leaugh Match
...,...,...,...,...,...,...
1032,2008,"ROYAL CHALLENGERS BANGALORE vs MUMBAI INDIANS,...",ROYAL CHALLENGERS BANGALORE,MUMBAI INDIANS,Mumbai Indians,Leaugh Match
1033,2008,"PUNJAB KINGS vs RAJASTHAN ROYALS, 56th match",PUNJAB KINGS,RAJASTHAN ROYALS,Kings XI Punjab,Leaugh Match
1034,2008,"DELHI CAPITALS vs RAJASTHAN ROYALS, 1st Semi-F...",DELHI CAPITALS,RAJASTHAN ROYALS,Rajasthan Royals,Semi Final
1035,2008,"CHENNAI SUPER KINGS vs PUNJAB KINGS, 2nd Semi-...",CHENNAI SUPER KINGS,PUNJAB KINGS,Chennai Super Kings,Semi Final
1036,2008,"CHENNAI SUPER KINGS vs RAJASTHAN ROYALS, Final",CHENNAI SUPER KINGS,RAJASTHAN ROYALS,Rajasthan Royals,Final

In [168]:
other_data

,IPL Edition,Team 1,Team 2,Winner
0,2023,GUJARAT TITANS,CHENNAI SUPER KINGS,Gujarat Titans
1,2023,PUNJAB KINGS,KOLKATA KNIGHT RIDERS,Punjab Kings
2,2023,LUCKNOW SUPER GIANTS,DELHI CAPITALS,Lucknow Super Giants
3,2023,SUNRISERS HYDERABAD,RAJASTHAN ROYALS,Rajasthan Royals
4,2023,ROYAL CHALLENGERS BANGALORE,MUMBAI INDIANS,Royal Challengers Bangalore
...,...,...,...,...
1032,2008,ROYAL CHALLENGERS BANGALORE,MUMBAI INDIANS,Mumbai Indians
1033,2008,PUNJAB KINGS,RAJASTHAN ROYALS,Kings XI Punjab
1034,2008,DELHI CAPITALS,RAJASTHAN ROYALS,Rajasthan Royals
1035,2008,CHENNAI SUPER KINGS,PUNJAB KINGS,Chennai Super Kings
1036,2008,CHENNAI SUPER KINGS,RAJASTHAN ROYALS,Rajasthan Royals

In [169]:
new_data = pd.concat([other_data,match_detail],axis=1)

In [170]:
new_data

,IPL Edition,Team 1,Team 2,Winner,Match Details
0,2023,GUJARAT TITANS,CHENNAI SUPER KINGS,Gujarat Titans,Leaugh Match
1,2023,PUNJAB KINGS,KOLKATA KNIGHT RIDERS,Punjab Kings,Leaugh Match
2,2023,LUCKNOW SUPER GIANTS,DELHI CAPITALS,Lucknow Super Giants,Leaugh Match
3,2023,SUNRISERS HYDERABAD,RAJASTHAN ROYALS,Rajasthan Royals,Leaugh Match
4,2023,ROYAL CHALLENGERS BANGALORE,MUMBAI INDIANS,Royal Challengers Bangalore,Leaugh Match
...,...,...,...,...,...
1032,2008,ROYAL CHALLENGERS BANGALORE,MUMBAI INDIANS,Mumbai Indians,Leaugh Match
1033,2008,PUNJAB KINGS,RAJASTHAN ROYALS,Kings XI Punjab,Leaugh Match
1034,2008,DELHI CAPITALS,RAJASTHAN ROYALS,Rajasthan Royals,Semi Final
1035,2008,CHENNAI SUPER KINGS,PUNJAB KINGS,Chennai Super Kings,Semi Final
1036,2008,CHENNAI SUPER KINGS,RAJASTHAN ROYALS,Rajasthan Royals,Final

In [171]:
new_data["Match Details"].unique()

array(['Leaugh Match', 'Qualifier 1', 'Eliminator', 'Qualifier 2',
       'Final', 'Semi Final'], dtype=object)

In [172]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
new_data['IPL Edition'] = label_encoder.fit_transform(new_data['IPL Edition'])

In [173]:
new_data

,IPL Edition,Team 1,Team 2,Winner,Match Details
0,15,GUJARAT TITANS,CHENNAI SUPER KINGS,Gujarat Titans,Leaugh Match
1,15,PUNJAB KINGS,KOLKATA KNIGHT RIDERS,Punjab Kings,Leaugh Match
2,15,LUCKNOW SUPER GIANTS,DELHI CAPITALS,Lucknow Super Giants,Leaugh Match
3,15,SUNRISERS HYDERABAD,RAJASTHAN ROYALS,Rajasthan Royals,Leaugh Match
4,15,ROYAL CHALLENGERS BANGALORE,MUMBAI INDIANS,Royal Challengers Bangalore,Leaugh Match
...,...,...,...,...,...
1032,0,ROYAL CHALLENGERS BANGALORE,MUMBAI INDIANS,Mumbai Indians,Leaugh Match
1033,0,PUNJAB KINGS,RAJASTHAN ROYALS,Kings XI Punjab,Leaugh Match
1034,0,DELHI CAPITALS,RAJASTHAN ROYALS,Rajasthan Royals,Semi Final
1035,0,CHENNAI SUPER KINGS,PUNJAB KINGS,Chennai Super Kings,Semi Final
1036,0,CHENNAI SUPER KINGS,RAJASTHAN ROYALS,Rajasthan Royals,Final

In [174]:
new_data["IPL Edition"].unique()

array([15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [175]:
new_data.drop(columns=['IPL Edition'],axis=1,inplace=True)

In [176]:
new_data

,Team 1,Team 2,Winner,Match Details
0,GUJARAT TITANS,CHENNAI SUPER KINGS,Gujarat Titans,Leaugh Match
1,PUNJAB KINGS,KOLKATA KNIGHT RIDERS,Punjab Kings,Leaugh Match
2,LUCKNOW SUPER GIANTS,DELHI CAPITALS,Lucknow Super Giants,Leaugh Match
3,SUNRISERS HYDERABAD,RAJASTHAN ROYALS,Rajasthan Royals,Leaugh Match
4,ROYAL CHALLENGERS BANGALORE,MUMBAI INDIANS,Royal Challengers Bangalore,Leaugh Match
...,...,...,...,...
1032,ROYAL CHALLENGERS BANGALORE,MUMBAI INDIANS,Mumbai Indians,Leaugh Match
1033,PUNJAB KINGS,RAJASTHAN ROYALS,Kings XI Punjab,Leaugh Match
1034,DELHI CAPITALS,RAJASTHAN ROYALS,Rajasthan Royals,Semi Final
1035,CHENNAI SUPER KINGS,PUNJAB KINGS,Chennai Super Kings,Semi Final
1036,CHENNAI SUPER KINGS,RAJASTHAN ROYALS,Rajasthan Royals,Final

In [177]:
Match = pd.get_dummies(new_data["Match Details"],drop_first=True)

In [178]:
Match

      Final  Leaugh Match  Qualifier 1  Qualifier 2  Semi Final
0         0             1            0            0           0
1         0             1            0            0           0
2         0             1            0            0           0
3         0             1            0            0           0
4         0             1            0            0           0
...     ...           ...          ...          ...         ...
1032      0             1            0            0           0
1033      0             1            0            0           0
1034      0             0            0            0           1
1035      0             0            0            0           1
1036      1             0            0            0           0

[1037 rows x 5 columns]

In [179]:
new_data.drop(columns=["Match Details"],axis=1,inplace=True)

In [180]:
new_data = pd.concat([new_data,Match],axis=1)

In [181]:
new_data

,Team 1,Team 2,Winner,Final,Leaugh Match,Qualifier 1,Qualifier 2,Semi Final
0,GUJARAT TITANS,CHENNAI SUPER KINGS,Gujarat Titans,0,1,0,0,0
1,PUNJAB KINGS,KOLKATA KNIGHT RIDERS,Punjab Kings,0,1,0,0,0
2,LUCKNOW SUPER GIANTS,DELHI CAPITALS,Lucknow Super Giants,0,1,0,0,0
3,SUNRISERS HYDERABAD,RAJASTHAN ROYALS,Rajasthan Royals,0,1,0,0,0
4,ROYAL CHALLENGERS BANGALORE,MUMBAI INDIANS,Royal Challengers Bangalore,0,1,0,0,0
...,...,...,...,...,...,...,...,...
1032,ROYAL CHALLENGERS BANGALORE,MUMBAI INDIANS,Mumbai Indians,0,1,0,0,0
1033,PUNJAB KINGS,RAJASTHAN ROYALS,Kings XI Punjab,0,1,0,0,0
1034,DELHI CAPITALS,RAJASTHAN ROYALS,Rajasthan Royals,0,0,0,0,1
1035,CHENNAI SUPER KINGS,PUNJAB KINGS,Chennai Super Kings,0,0,0,0,1
1036,CHENNAI SUPER KINGS,RAJASTHAN ROYALS,Rajasthan Royals,1,0,0,0,0

In [182]:
new_data.columns = ["Home Team","Away Team","Winner","Final","Leaugh Match","Qualifier 1","Qualifier 2","Semi Final"]

In [183]:
new_data

,Home Team,Away Team,Winner,Final,Leaugh Match,Qualifier 1,Qualifier 2,Semi Final
0,GUJARAT TITANS,CHENNAI SUPER KINGS,Gujarat Titans,0,1,0,0,0
1,PUNJAB KINGS,KOLKATA KNIGHT RIDERS,Punjab Kings,0,1,0,0,0
2,LUCKNOW SUPER GIANTS,DELHI CAPITALS,Lucknow Super Giants,0,1,0,0,0
3,SUNRISERS HYDERABAD,RAJASTHAN ROYALS,Rajasthan Royals,0,1,0,0,0
4,ROYAL CHALLENGERS BANGALORE,MUMBAI INDIANS,Royal Challengers Bangalore,0,1,0,0,0
...,...,...,...,...,...,...,...,...
1032,ROYAL CHALLENGERS BANGALORE,MUMBAI INDIANS,Mumbai Indians,0,1,0,0,0
1033,PUNJAB KINGS,RAJASTHAN ROYALS,Kings XI Punjab,0,1,0,0,0
1034,DELHI CAPITALS,RAJASTHAN ROYALS,Rajasthan Royals,0,0,0,0,1
1035,CHENNAI SUPER KINGS,PUNJAB KINGS,Chennai Super Kings,0,0,0,0,1
1036,CHENNAI SUPER KINGS,RAJASTHAN ROYALS,Rajasthan Royals,1,0,0,0,0

In [184]:
new_data["Home Team"] == new_data["Winner"]

0       False
1       False
2       False
3       False
4       False
        ...
1032    False
1033    False
1034    False
1035    False
1036    False
Length: 1037, dtype: bool

In [185]:


df = new_data.applymap(lambda x: x.lower() if isinstance(x, str) else x)

In [186]:
df

,Home Team,Away Team,Winner,Final,Leaugh Match,Qualifier 1,Qualifier 2,Semi Final
0,gujarat titans,chennai super kings,gujarat titans,0,1,0,0,0
1,punjab kings,kolkata knight riders,punjab kings,0,1,0,0,0
2,lucknow super giants,delhi capitals,lucknow super giants,0,1,0,0,0
3,sunrisers hyderabad,rajasthan royals,rajasthan royals,0,1,0,0,0
4,royal challengers bangalore,mumbai indians,royal challengers bangalore,0,1,0,0,0
...,...,...,...,...,...,...,...,...
1032,royal challengers bangalore,mumbai indians,mumbai indians,0,1,0,0,0
1033,punjab kings,rajasthan royals,kings xi punjab,0,1,0,0,0
1034,delhi capitals,rajasthan royals,rajasthan royals,0,0,0,0,1
1035,chennai super kings,punjab kings,chennai super kings,0,0,0,0,1
1036,chennai super kings,rajasthan royals,rajasthan royals,1,0,0,0,0

In [187]:
df["Away Team"]

0         chennai super kings
1       kolkata knight riders
2              delhi capitals
3            rajasthan royals
4              mumbai indians
                ...
1032           mumbai indians
1033         rajasthan royals
1034         rajasthan royals
1035             punjab kings
1036         rajasthan royals
Name: Away Team, Length: 1037, dtype: object

In [188]:
df["Winner"][3]

'rajasthan royals '

In [189]:
df["Away Team"][3]

'rajasthan royals'

In [190]:
arr  = np.array(df["Away Team"])

In [191]:
arr

array(['chennai super kings', 'kolkata knight riders', 'delhi capitals',
       ..., 'rajasthan royals', 'punjab kings', 'rajasthan royals'],
      dtype=object)

In [192]:
arr2 = np.array(df["Winner"])

In [193]:
arr2

array(['gujarat titans ', 'punjab kings ', 'lucknow super giants ', ...,
       'rajasthan royals ', 'chennai super kings ', 'rajasthan royals '],
      dtype=object)

In [194]:
np.where(arr == arr2)

(array([], dtype=int64),)

In [195]:
df['Home_Winner'] = (df['Winner'] == df['Home Team']).astype(int)

In [196]:
df.drop(columns=['Home_Winner'],axis=1,inplace=True)

In [197]:
df

,Home Team,Away Team,Winner,Final,Leaugh Match,Qualifier 1,Qualifier 2,Semi Final
0,gujarat titans,chennai super kings,gujarat titans,0,1,0,0,0
1,punjab kings,kolkata knight riders,punjab kings,0,1,0,0,0
2,lucknow super giants,delhi capitals,lucknow super giants,0,1,0,0,0
3,sunrisers hyderabad,rajasthan royals,rajasthan royals,0,1,0,0,0
4,royal challengers bangalore,mumbai indians,royal challengers bangalore,0,1,0,0,0
...,...,...,...,...,...,...,...,...
1032,royal challengers bangalore,mumbai indians,mumbai indians,0,1,0,0,0
1033,punjab kings,rajasthan royals,kings xi punjab,0,1,0,0,0
1034,delhi capitals,rajasthan royals,rajasthan royals,0,0,0,0,1
1035,chennai super kings,punjab kings,chennai super kings,0,0,0,0,1
1036,chennai super kings,rajasthan royals,rajasthan royals,1,0,0,0,0

In [198]:
import pandas as pd


df['Home_Winner'] = (df['Winner'].str.lower().str.strip() == df['Home Team'].str.lower().str.strip()).astype(int)

In [199]:
df

,Home Team,Away Team,Winner,Final,Leaugh Match,Qualifier 1,Qualifier 2,Semi Final,Home_Winner
0,gujarat titans,chennai super kings,gujarat titans,0,1,0,0,0,1
1,punjab kings,kolkata knight riders,punjab kings,0,1,0,0,0,1
2,lucknow super giants,delhi capitals,lucknow super giants,0,1,0,0,0,1
3,sunrisers hyderabad,rajasthan royals,rajasthan royals,0,1,0,0,0,0
4,royal challengers bangalore,mumbai indians,royal challengers bangalore,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...
1032,royal challengers bangalore,mumbai indians,mumbai indians,0,1,0,0,0,0
1033,punjab kings,rajasthan royals,kings xi punjab,0,1,0,0,0,0
1034,delhi capitals,rajasthan royals,rajasthan royals,0,0,0,0,1,0
1035,chennai super kings,punjab kings,chennai super kings,0,0,0,0,1,1
1036,chennai super kings,rajasthan royals,rajasthan royals,1,0,0,0,0,0

In [200]:
df.drop(columns=["Winner"],axis=1)

,Home Team,Away Team,Final,Leaugh Match,Qualifier 1,Qualifier 2,Semi Final,Home_Winner
0,gujarat titans,chennai super kings,0,1,0,0,0,1
1,punjab kings,kolkata knight riders,0,1,0,0,0,1
2,lucknow super giants,delhi capitals,0,1,0,0,0,1
3,sunrisers hyderabad,rajasthan royals,0,1,0,0,0,0
4,royal challengers bangalore,mumbai indians,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...
1032,royal challengers bangalore,mumbai indians,0,1,0,0,0,0
1033,punjab kings,rajasthan royals,0,1,0,0,0,0
1034,delhi capitals,rajasthan royals,0,0,0,0,1,0
1035,chennai super kings,punjab kings,0,0,0,0,1,1
1036,chennai super kings,rajasthan royals,1,0,0,0,0,0

In [201]:
new_df = df.drop(columns=["Winner"],axis=1)

In [202]:
new_df

,Home Team,Away Team,Final,Leaugh Match,Qualifier 1,Qualifier 2,Semi Final,Home_Winner
0,gujarat titans,chennai super kings,0,1,0,0,0,1
1,punjab kings,kolkata knight riders,0,1,0,0,0,1
2,lucknow super giants,delhi capitals,0,1,0,0,0,1
3,sunrisers hyderabad,rajasthan royals,0,1,0,0,0,0
4,royal challengers bangalore,mumbai indians,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...
1032,royal challengers bangalore,mumbai indians,0,1,0,0,0,0
1033,punjab kings,rajasthan royals,0,1,0,0,0,0
1034,delhi capitals,rajasthan royals,0,0,0,0,1,0
1035,chennai super kings,punjab kings,0,0,0,0,1,1
1036,chennai super kings,rajasthan royals,1,0,0,0,0,0

Home team 1 and away team 0

In [203]:
#perform encoding

df_encoded = pd.get_dummies(new_df, columns=['Home Team', 'Away Team'], prefix=['Home', 'Away'])

In [204]:
df_encoded

,Final,Leaugh Match,Qualifier 1,Qualifier 2,Semi Final,Home_Winner,Home_chennai super kings,Home_deccan chargers,Home_delhi capitals,Home_gujarat lions,...,Away_kochi tuskers kerala,Away_kolkata knight riders,Away_lucknow super giants,Away_mumbai indians,Away_pune warriors,Away_punjab kings,Away_rajasthan royals,Away_rising pune supergiant,Away_royal challengers bangalore,Away_sunrisers hyderabad
0,0,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,0,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,0,1,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1032,0,1,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1033,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1034,0,0,0,0,1,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
1035,0,0,0,0,1,1,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1036,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [205]:
df_encoded.corr()

,Final,Leaugh Match,Qualifier 1,Qualifier 2,Semi Final,Home_Winner,Home_chennai super kings,Home_deccan chargers,Home_delhi capitals,Home_gujarat lions,...,Away_kochi tuskers kerala,Away_kolkata knight riders,Away_lucknow super giants,Away_mumbai indians,Away_pune warriors,Away_punjab kings,Away_rajasthan royals,Away_rising pune supergiant,Away_royal challengers bangalore,Away_sunrisers hyderabad
Final,1.000000,-0.511954,-0.014546,-0.014546,-0.009849,0.039667,0.187511,-0.025521,-0.047359,-0.016161,...,-0.010643,0.019486,-0.015103,0.019926,-0.019443,-0.022036,0.003184,-0.015640,-0.021409,0.017893
Leaugh Match,-0.511954,1.000000,-0.446815,-0.446815,-0.302519,-0.032611,-0.133920,0.049849,-0.008127,-0.034432,...,0.020789,-0.075511,0.029500,-0.015078,0.037979,0.064216,-0.002395,-0.003515,0.011342,-0.000564
Qualifier 1,-0.014546,-0.446815,1.000000,-0.012695,-0.008595,-0.046604,0.012279,-0.022274,0.039084,0.056216,...,-0.009289,0.009334,-0.013181,0.009692,-0.016969,-0.040181,-0.011890,0.058941,-0.012191,-0.033234
Qualifier 2,-0.014546,-0.446815,-0.012695,1.000000,-0.008595,0.040789,0.039084,-0.022274,0.012279,0.056216,...,-0.009289,0.061512,-0.013181,-0.016482,-0.016969,-0.040181,-0.011890,-0.013650,0.043014,-0.001294
Semi Final,-0.009849,-0.302519,-0.008595,-0.008595,1.000000,0.009866,0.050661,-0.015080,0.050661,-0.009550,...,-0.006289,-0.029008,-0.008924,0.009516,-0.011489,0.012982,0.013836,-0.009242,-0.026942,-0.022501
Home_Winner,0.039667,-0.032611,-0.046604,0.040789,0.009866,1.000000,0.176755,-0.040878,-0.190135,-0.031146,...,0.022536,0.005272,-0.035425,-0.062626,0.039285,0.024605,0.020581,-0.041340,0.005417,0.034562
Home_chennai super kings,0.187511,-0.133920,0.012279,0.039084,0.050661,0.176755,1.000000,-0.072518,-0.134573,-0.045923,...,0.006182,0.022102,-0.017071,0.032250,0.005507,0.010581,0.014095,-0.044443,0.003416,0.001706
Home_deccan chargers,-0.025521,0.049849,-0.022274,-0.022274,-0.015080,-0.040878,-0.072518,1.000000,-0.072518,-0.024747,...,-0.016297,0.016376,-0.023126,0.017005,0.039066,0.025631,0.027752,-0.023949,-0.005246,-0.058309
Home_delhi capitals,-0.047359,-0.008127,0.039084,0.012279,0.050661,-0.190135,-0.134573,-0.072518,1.000000,-0.045923,...,0.006182,0.040057,-0.017071,0.014236,0.005507,0.029435,0.004560,0.005516,0.012915,0.023689
Home_gujarat lions,-0.016161,-0.034432,0.056216,0.056216,-0.009550,-0.031146,-0.045923,-0.024747,-0.045923,1.000000,...,-0.010320,-0.000500,-0.014644,-0.000137,-0.018854,0.004817,-0.043995,0.115893,0.030539,0.049575
Home_gujarat titans,0.040989,-0.091056,0.117753,0.051389,-0.010139,0.061859,-0.048756,-0.026273,-0.048756,-0.016638,...,-0.010957,-0.028313,0.112415,0.016579,-0.020017,-0.024058,0.024106,-0.016102,-0.023424,0.015219
Home_kochi tuskers kerala,-0.010643,0.020789,-0.009289,-0.009289,-0.006289,-0.001214,-0.030242,-0.016297,-0.030242,-0.010320,...,-0.006796,0.004102,-0.009644,-0.031210,-0.012416,0.007825,0.008677,-0.009987,0.008391,-0.024316
Home_kolkata knight riders,-0.021409,0.063153,-0.039793,-0.039793,-0.026942,0.073542,-0.129558,-0.069815,-0.129558,-0.044211,...,0.008391,-0.134294,0.011907,0.014685,-0.011483,0.029364,0.032966,0.008656,0.031755,0.020321
Home_lucknow super giants,-0.016161,-0.034432,-0.014105,-0.014105,-0.009550,0.000411,-0.045923,-0.024747,-0.045923,-0.015671,...,-0.010320,-0.024050,-0.014644,0.023491,-0.018854,-0.019913,-0.018982,-0.015166,0.030539,-0.008091
Home_mumbai indians,0.001568,-0.024912,0.014213,0.041506,-0.027336,0.101456,-0.131451,-0.070835,-0.131451,-0.044857,...,0.007546,0.009996,-0.015605,-0.135660,0.007894,0.016188,0.029395,0.032890,0.008841,0.017407
Home_pune warriors,-0.019443,0.037979,-0.016969,-0.016969,-0.011489,-0.053152,-0.055249,-0.029772,-0.055249,-0.018854,...,0.067554,0.001863,-0.017619,0.002307,-0.022682,0.008383,-0.011062,-0.018246,-0.011483,-0.020292
Home_punjab kings,-0.045594,0.063153,-0.012191,-0.012191,-0.026942,-0.267085,-0.129558,-0.069815,-0.129558,-0.044211,...,-0.029115,0.013612,0.011907,0.014685,0.009371,-0.125945,0.023148,0.008656,0.021975,0.009004
Home_rajasthan royals,-0.040998,0.051883,-0.035781,-0.005737,-0.024226,0.105111,-0.116497,-0.062777,-0.116497,-0.039754,...,0.014645,-0.000010,0.020782,0.000915,0.020269,0.002975,-0.111606,-0.038473,0.036885,0.017202
Home_rising pune supergiant,0.047964,-0.003515,-0.013650,-0.013650,-0.009242,-0.025052,-0.044443,-0.023949,-0.044443,-0.015166,...,-0.009987,0.002555,-0.014172,0.027308,-0.018246,0.007853,-0.042577,-0.014677,0.008656,0.023794
Home_royal challengers bangalore,-0.003008,-0.002795,-0.016482,-0.042657,0.047913,0.043087,-0.138882,-0.074840,-0.138882,-0.047393,...,0.004356,0.022596,-0.019054,0.014978,0.002307,0.012267,0.015909,0.002917,-0.133706,0.006386
Home_sunrisers hyderabad,-0.038328,0.015238,-0.001685,-0.001685,-0.022649,0.009884,-0.108911,-0.058689,-0.108911,-0.037166,...,-0.024475,0.036051,0.026521,0.015686,-0.020714,0.017010,-0.002648,0.023236,0.018962,-0.087571
Away_chennai super kings,0.006575,-0.062599,0.133646,-0.009408,0.016230,-0.026978,-0.123782,-0.016506,0.004206,-0.042240,...,-0.027817,-0.128307,-0.039473,-0.127746,-0.050819,-0.120331,-0.118585,-0.040879,-0.119169,-0.099527
Away_deccan chargers,0.016108,-0.017275,-0.021673,-0.021673,0.122415,-0.001335,0.041988,-0.038025,0.009830,-0.024080,...,-0.015857,-0.073143,-0.022502,-0.072823,-0.028970,-0.068596,-0.067601,-0.023303,-0.067934,-0.056737
Away_delhi capitals,-0.045594,0.063153,-0.039793,0.015411,-0.026942,0.036383,0.031911,0.027039,-0.129558,0.005622,...,-0.029115,-0.134294,-0.041315,-0.133706,-0.053190,-0.125945,-0.124118,-0.042786,-0.124729,-0.104171
Away_gujarat lions,-0.015103,0.029500,-0.013181,-0.013181,-0.008924,-0.018574,-0.042915,-0.023126,0.008772,-0.014644,...,-0.009644,-0.044483,-0.013685,-0.044289,-0.017619,-0.041718,-0.041113,-0.014172,-0.041315,-0.034506
Away_gujarat titans,0.107067,-0.034432,-0.014105,-0.014105,-0.009550,-0.046924,0.026672,-0.024747,-0.021725,-0.015671,...,-0.010320,-0.047601,-0.014644,-0.047393,-0.018854,-0.044642,-0.043995,-0.015166,-0.044211,-0.036924
Away_kochi tuskers kerala,-0.010643,0.020789,-0.009289,-0.009289,-0.006289,0.022536,0.006182,-0.016297,0.006182,-0.010320,...,1.000000,-0.031347,-0.009644,-0.031210,-0.012416,-0.029399,-0.028972,-0.009987,-0.029115,-0.024316
Away_kolkata knight riders,0.019486,-0.075511,0.009334,0.061512,-0.029008,0.005272,0.022102,0.016376,0.040057,-0.000500,...,-0.031347,1.000000,-0.044483,-0.143959,-0.057269,-0.135603,-0.133636,-0.046067,-0.134294,-0.112160
Away_lucknow super giants,-0.015103,0.029500,-0.013181,-0.013181,-0.008924,-0.035425,-0.017071,-0.023126,-0.017071,-0.014644,...,-0.009644,-0.044483,1.000000,-0.044289,-0.017619,-0.041718,-0.041113,-0.014172,-0.041315,-0.034506
Away_mumbai indians,0.019926,-0.015078,0.009692,-0.016482,0.009516,-0.062626,0.032250,0.017005,0.014236,-0.000137,...,-0.031210,-0.143959,-0.044289,1.000000,-0.057018,-0.135010,-0.133051,-0.045866,-0.133706,-0.111669
Away_pune warriors,-0.019443,0.037979,-0.016969,-0.016969,-0.011489,0.039285,0.005507,0.039066,0.005507,-0.018854,...,-0.012416,-0.057269,-0.017619,-0.057018,1.000000,-0.053709,-0.052929,-0.018246,-0.053190,-0.044423
Away_punjab kings,-0.022036,0.064216,-0.040181,-0.040181,0.012982,0.024605,0.010581,0.025631,0.029435,0.004817,...,-0.029399,-0.135603,-0.041718,-0.135010,-0.053709,1.000000,-0.125329,-0.043204,-0.125945,-0.105187
Away_rajasthan royals,0.003184,-0.002395,-0.011890,-0.011890,0.013836,0.020581,0.014095,0.027752,0.004560,-0.043995,...,-0.028972,-0.133636,-0.041113,-0.133051,-0.052929,-0.125329,1.000000,-0.042577,-0.124118,-0.103661
Away_rising pune supergiant,-0.015640,-0.003515,0.058941,-0.013650,-0.009242,-0.041340,-0.044443,-0.023949,0.005516,0.115893,...,-0.009987,-0.046067,-0.014172,-0.045866,-0.018246,-0.043204,-0.042577,1.000000,-0.042786,-0.035734
Away_royal challengers bangalore,-0.021409,0.011342,-0.012191,0.043014,-0.026942,0.005417,0.003416,-0.005246,0.012915,0.030539,...,-0.029115,-0.134294,-0.041315,-0.133706,-0.053190,-0.125945,-0.124118,-0.042786,1.000000,-0.104171
Away_sunrisers hyderabad,0.017893,-0.000564,-0.033234,-0.001294,-0.022501,0.034562,0.001706,-0.058309,0.023689,0.049575,...,-0.024316,-0.112160,-0.034506,-0.111669,-0.044423,-0.105187,-0.103661,-0.035734,-0.104171,1.000000

In [206]:
#train ,test data

from sklearn.model_selection import train_test_split

In [207]:
X = df_encoded.drop(columns=['Home_Winner'] ,axis=1)

In [208]:
X

,Final,Leaugh Match,Qualifier 1,Qualifier 2,Semi Final,Home_chennai super kings,Home_deccan chargers,Home_delhi capitals,Home_gujarat lions,Home_gujarat titans,...,Away_kochi tuskers kerala,Away_kolkata knight riders,Away_lucknow super giants,Away_mumbai indians,Away_pune warriors,Away_punjab kings,Away_rajasthan royals,Away_rising pune supergiant,Away_royal challengers bangalore,Away_sunrisers hyderabad
0,0,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,0,1,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1032,0,1,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1033,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1034,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
1035,0,0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1036,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [209]:

y = df_encoded["Home_Winner"]

In [210]:
y

0       1
1       1
2       1
3       0
4       1
       ..
1032    0
1033    0
1034    0
1035    1
1036    0
Name: Home_Winner, Length: 1037, dtype: int64

In [211]:
train_x , test_x,train_y,test_y = train_test_split(X,y,test_size=0.25,random_state=42)

In [212]:
class_priors = np.bincount(train_y) / len(train_y)

In [213]:
#model selection
#model creation
from sklearn.naive_bayes import MultinomialNB

In [214]:
model = MultinomialNB()

In [215]:
model.fit(train_x,train_y)

MultinomialNB()

In [216]:
y_pred = model.predict(test_x)

In [217]:
#check accurecy 

from sklearn.metrics import accuracy_score,classification_report,f1_score

In [218]:
accuracy_score = accuracy_score(test_y,y_pred)
print(f"{accuracy_score * 100:.2f}%")

61.15%

In [219]:
from sklearn.ensemble import RandomForestClassifier

In [220]:
r_model = RandomForestClassifier(max_depth=20)

In [221]:
r_model.fit(train_x,train_y)

RandomForestClassifier(max_depth=20)

In [222]:
ypred = r_model.predict(test_x)

In [225]:
from sklearn.metrics import accuracy_score
accuracy_score(test_y,ypred)

0.5846153846153846

In [227]:
from sklearn.tree import DecisionTreeClassifier

In [228]:
D_model = DecisionTreeClassifier()

In [229]:
D_model.fit(train_x,train_y)

DecisionTreeClassifier()

In [230]:
ypred = D_model.predict(test_x)

In [231]:
accuracy_score(test_y,ypred)

0.573076923076923

In [ ]:
from sklearn.svm import SVC

In [ ]:
svc_model  = SVC(C=1)

In [ ]:
svc_model.fit(train_x, train_y)

SVC(C=1)

In [ ]:
ypred = svc_model.predict(test_x)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(test_y,ypred)

0.573076923076923

In [ ]:
test_x

,Final,Leaugh Match,Qualifier 1,Qualifier 2,Semi Final,Home_chennai super kings,Home_deccan chargers,Home_delhi capitals,Home_gujarat lions,Home_gujarat titans,...,Away_kochi tuskers kerala,Away_kolkata knight riders,Away_lucknow super giants,Away_mumbai indians,Away_pune warriors,Away_punjab kings,Away_rajasthan royals,Away_rising pune supergiant,Away_royal challengers bangalore,Away_sunrisers hyderabad
622,0,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
109,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
649,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
458,0,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
541,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
516,0,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
65,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
355,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
873,0,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
254,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [250]:
test_y

622    0
109    0
649    1
458    1
541    0
      ..
516    1
65     0
355    0
873    1
254    1
Name: Home_Winner, Length: 260, dtype: int64

In [247]:
pred_data = [0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1]

In [249]:
model.predict([pred_data])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(

array([1])

In [ ]:

data

,IPL Edition,Match Details,Team 1,Team 2,Winner
0,2023,"GUJARAT TITANS vs CHENNAI SUPER KINGS, 1st Match",GUJARAT TITANS,CHENNAI SUPER KINGS,Gujarat Titans
1,2023,"PUNJAB KINGS vs KOLKATA KNIGHT RIDERS, 2nd Match",PUNJAB KINGS,KOLKATA KNIGHT RIDERS,Punjab Kings
2,2023,"LUCKNOW SUPER GIANTS vs DELHI CAPITALS, 3rd Match",LUCKNOW SUPER GIANTS,DELHI CAPITALS,Lucknow Super Giants
3,2023,"SUNRISERS HYDERABAD vs RAJASTHAN ROYALS, 4th M...",SUNRISERS HYDERABAD,RAJASTHAN ROYALS,Rajasthan Royals
4,2023,"ROYAL CHALLENGERS BANGALORE vs MUMBAI INDIANS,...",ROYAL CHALLENGERS BANGALORE,MUMBAI INDIANS,Royal Challengers Bangalore
...,...,...,...,...,...
1032,2008,"ROYAL CHALLENGERS BANGALORE vs MUMBAI INDIANS,...",ROYAL CHALLENGERS BANGALORE,MUMBAI INDIANS,Mumbai Indians
1033,2008,"PUNJAB KINGS vs RAJASTHAN ROYALS, 56th match",PUNJAB KINGS,RAJASTHAN ROYALS,Kings XI Punjab
1034,2008,"DELHI CAPITALS vs RAJASTHAN ROYALS, 1st Semi-F...",DELHI CAPITALS,RAJASTHAN ROYALS,Rajasthan Royals
1035,2008,"CHENNAI SUPER KINGS vs PUNJAB KINGS, 2nd Semi-...",CHENNAI SUPER KINGS,PUNJAB KINGS,Chennai Super Kings
1036,2008,"CHENNAI SUPER KINGS vs RAJASTHAN ROYALS, Final",CHENNAI SUPER KINGS,RAJASTHAN ROYALS,Rajasthan Royals

In [ ]:
df_encoded.columns.value_counts

<bound method IndexOpsMixin.value_counts of Index(['Final', 'Leaugh Match', 'Qualifier 1', 'Qualifier 2', 'Semi Final',
       'Home_Winner', 'Home_chennai super kings', 'Home_deccan chargers',
       'Home_delhi capitals', 'Home_gujarat lions', 'Home_gujarat titans',
       'Home_kochi tuskers kerala', 'Home_kolkata knight riders',
       'Home_lucknow super giants', 'Home_mumbai indians',
       'Home_pune warriors', 'Home_punjab kings', 'Home_rajasthan royals',
       'Home_rising pune supergiant', 'Home_royal challengers bangalore',
       'Home_sunrisers hyderabad', 'Away_chennai super kings',
       'Away_deccan chargers', 'Away_delhi capitals', 'Away_gujarat lions',
       'Away_gujarat titans', 'Away_kochi tuskers kerala',
       'Away_kolkata knight riders', 'Away_lucknow super giants',
       'Away_mumbai indians', 'Away_pune warriors', 'Away_punjab kings',
       'Away_rajasthan royals', 'Away_rising pune supergiant',
       'Away_royal challengers bangalore', 'Away_sunrisers hyderabad'],
      dtype='object')>

In [ ]:
prediction = [0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,]

In [ ]:
model.predict([prediction])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(

array([1])

In [ ]:
r_model.predict([prediction])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([1])

In [232]:
D_model.predict([prediction])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])

In [233]:
svc_model.predict([prediction])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

array([1])

In [234]:
#linear model 

from sklearn.linear_model import Perceptron

In [235]:
p_model = Perceptron()

In [236]:
p_model.fit(train_x,train_y)

Perceptron()

In [237]:
pred = p_model.predict(test_x)

In [238]:
accuracy_score(test_y,ypred)

0.573076923076923

In [246]:
p_model.predict([prediction])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but Perceptron was fitted with feature names
  warnings.warn(

array([1])

In [239]:
#KNN model

from sklearn.neighbors import KNeighborsClassifier

In [240]:
k_model = KNeighborsClassifier(n_neighbors=7)

In [241]:
k_model.fit(train_x,train_y)

KNeighborsClassifier(n_neighbors=7)

In [242]:
ypred = k_model.predict(test_x)

In [244]:
accuracy_score(test_y,ypred)

0.6076923076923076

In [245]:
k_model.predict([prediction])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array([0])

In [251]:
clr = classification_report(test_y,ypred)

In [252]:
print(clr)

              precision    recall  f1-score   support

           0       0.70      0.64      0.67       160
           1       0.49      0.55      0.52       100

    accuracy                           0.61       260
   macro avg       0.59      0.60      0.59       260
weighted avg       0.62      0.61      0.61       260

In [253]:
D_model.predict([pred_data])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])

In [254]:
r_model.predict([pred_data])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([1])

In [255]:
k_model.predict([pred_data])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array([1])

In [256]:
p_model.predict([pred_data])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but Perceptron was fitted with feature names
  warnings.warn(

array([1])

In [257]:
svc_model.predict([pred_data])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

array([1])

In [258]:
pred_data

[0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1]

In [259]:
new_pred_data = [0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0]

In [260]:
model.predict([new_pred_data])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(

array([0])

In [261]:
svc_model.predict([new_pred_data])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

array([0])

In [262]:
D_model.predict([new_pred_data])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])

In [263]:
r_model.predict([new_pred_data])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([0])

In [264]:
k_model.predict([new_pred_data])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array([0])